-- Insight Loop (Phase 2): durable observation facts, analysis windows,
-- findings and governance-draft proposals for native APL definitions.
--
-- The Insight Loop runs completely out-of-band: execution facts are tiny
-- terminal snapshots written inside the workflow transaction, while the
-- analyzer consumes them through bounded windows and never touches live
-- workflow rows. No PII ever reaches these tables (identifiers only).

-- Terminal execution facts per (process instance, node). One row per node
-- visit: external-task completion/failure, user-task completion, and each
-- decision-table application. Facts only exist for reached terminal states,
-- so the analyzer never sees in-flight work.
CREATE TABLE insight_execution_facts (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id                   VARCHAR(64)     NOT NULL,
    definition_key             VARCHAR(255)    NOT NULL,
    definition_deployment_id   VARCHAR(64)     NOT NULL,
    process_instance_id        VARCHAR(64)     NOT NULL,
    activity_id                VARCHAR(255)    NOT NULL,
    node_type                  VARCHAR(32)     NOT NULL
                               CONSTRAINT ck_insight_facts_node_type
                               CHECK (node_type IN ('EXTERNAL_TASK', 'USER_TASK', 'DECISION')),
    status                     VARCHAR(16)     NOT NULL
                               CONSTRAINT ck_insight_facts_status
                               CHECK (status IN ('SUCCESS', 'FAILED')),
    started_at                 TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms                BIGINT          NOT NULL,
    topic                      VARCHAR(255),
    decision_key               VARCHAR(255),
    matched_rule_indexes       VARCHAR(255),
    fallback_used              BOOLEAN
);

CREATE UNIQUE INDEX uq_insight_facts_node_visit
    ON insight_execution_facts (visit_id);
CREATE INDEX idx_insight_facts_definition_window
    ON insight_execution_facts (definition_deployment_id, ended_at);
CREATE INDEX idx_insight_facts_node
    ON insight_execution_facts (definition_deployment_id, node_type, activity_id, ended_at);

-- Completed analysis windows; the worker cursor (last COMPLETED ended_at)
-- makes each fact reach exactly one window across replicas.
CREATE TABLE insight_observation_windows (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    ended_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    status            VARCHAR(16) NOT NULL
                      CONSTRAINT ck_insight_window_status
                      CHECK (status IN ('ANALYZED', 'COMPLETED', 'FAILED')),
    facts_processed   INTEGER     NOT NULL DEFAULT 0,
    findings_count    INTEGER     NOT NULL DEFAULT 0,
    proposals_count    INTEGER     NOT NULL DEFAULT 0,
    completed_at       TIMESTAMP WITH TIME ZONE,
    error_message      TEXT
);
CREATE INDEX idx_insight_windows_ended ON insight_observation_windows (ended_at DESC);

-- One durable worker lease, portable across PostgreSQL and H2: replicas
-- acquire it in the same transaction as window processing, so a stale lease
-- can never double-process a window.
CREATE TABLE insight_worker_lease (
    singleton        BOOLEAN      NOT NULL DEFAULT TRUE PRIMARY KEY
                     CONSTRAINT ck_insight_lease_once CHECK (singleton),
    worker_id        VARCHAR(128) NOT NULL,
    acquired_at      TIMESTAMP WITH TIME ZONE NOT NULL,
    lease_expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
INSERT INTO insight_worker_lease (worker_id, acquired_at, lease_expires_at)
VALUES ('unacquired', now(), now());

-- Analyzer findings for a window, one row per (definition, node, signal).
CREATE TABLE insight_findings (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    window_id                  BIGINT NOT NULL
                               CONSTRAINT fk_findings_window
                               REFERENCES insight_observation_windows (id) ON DELETE CASCADE,
    definition_key             VARCHAR(255) NOT NULL,
    definition_deployment_id   VARCHAR(64)  NOT NULL,
    node_id                    VARCHAR(255) NOT NULL,
    node_type                  VARCHAR(32)  NOT NULL,
    signal_type                VARCHAR(32)  NOT NULL
                               CONSTRAINT ck_insight_findings_signal
                               CHECK (signal_type IN ('FAILURE_RATE', 'LATENCY_P95', 'FALLBACK_THRASH')),
    severity                   VARCHAR(16)  NOT NULL
                               CONSTRAINT ck_insight_findings_severity
                               CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH')),
    observed_value             DOUBLE PRECISION NOT NULL,
    threshold                  DOUBLE PRECISION NOT NULL,
    sample_count               INT          NOT NULL,
    summary                    TEXT         NOT NULL,
    created_at                 TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_insight_findings_window ON insight_findings (window_id);
CREATE INDEX idx_insight_findings_definition ON insight_findings (definition_deployment_id, node_id);

-- Governance proposals: a DRAFT full APL document (with embedded optimizer
-- `#` comments) targeting an immutable definition version. Review moves
-- DRAFT -> ADOPTED (new version via the schema dispatcher) or REJECTED.
CREATE TABLE insight_proposals (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    window_id               BIGINT
                            CONSTRAINT fk_proposals_window
                            REFERENCES insight_observation_windows (id) ON DELETE SET NULL,
    definition_key          VARCHAR(255) NOT NULL,
    definition_deployment_id VARCHAR(64) NOT NULL,
    target_version          INT          NOT NULL,
    target_checksum         VARCHAR(64)  NOT NULL,
    target_source           TEXT         NOT NULL,
    proposed_source         TEXT         NOT NULL,
    rationale               TEXT         NOT NULL,
    status                  VARCHAR(16)  NOT NULL DEFAULT 'DRAFT'
                            CONSTRAINT ck_insight_proposals_status
                            CHECK (status IN ('DRAFT', 'IN_REVIEW', 'ADOPTED', 'REJECTED', 'SUPERSEDED')),
    open_slot               BOOLEAN,
    required_approvals      INT          NOT NULL DEFAULT 1,
    required_groups        VARCHAR(1024) NOT NULL DEFAULT 'abada-insight-reviewer',
    approval_mode          VARCHAR(16)   NOT NULL DEFAULT 'PARALLEL'
                            CONSTRAINT ck_insight_proposal_approval_mode
                            CHECK (approval_mode IN ('PARALLEL', 'SEQUENTIAL')),
    adopted_deployment_id   VARCHAR(64),
    adopted_version         INT,
    created_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    entity_version          BIGINT       NOT NULL DEFAULT 0
);
CREATE INDEX idx_insight_proposals_status_created
    ON insight_proposals (status, created_at DESC);
CREATE INDEX idx_insight_proposals_definition
    ON insight_proposals (definition_deployment_id, status);
CREATE UNIQUE INDEX uq_insight_open_proposal_per_deployment
    ON insight_proposals (definition_deployment_id, open_slot);

-- Versioned approval policy. A proposal snapshots these values when it is
-- created, so a later policy update never changes an in-flight review.
CREATE TABLE insight_approval_policies (
    definition_key       VARCHAR(255) PRIMARY KEY,
    policy_version       BIGINT       NOT NULL DEFAULT 0,
    required_approvals   INT          NOT NULL DEFAULT 1 CHECK (required_approvals BETWEEN 1 AND 20),
    required_groups      VARCHAR(1024) NOT NULL DEFAULT 'abada-insight-reviewer',
    approval_mode        VARCHAR(16)  NOT NULL DEFAULT 'PARALLEL'
                         CONSTRAINT ck_insight_policy_approval_mode
                         CHECK (approval_mode IN ('PARALLEL', 'SEQUENTIAL')),
    updated_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_by           VARCHAR(255) NOT NULL
);

CREATE TABLE insight_proposal_reviews (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    proposal_id          BIGINT NOT NULL
                         CONSTRAINT fk_insight_reviews_proposal
                         REFERENCES insight_proposals (id) ON DELETE CASCADE,
    actor                VARCHAR(255) NOT NULL,
    actor_groups         VARCHAR(2048) NOT NULL,
    decision             VARCHAR(16) NOT NULL
                         CONSTRAINT ck_insight_review_decision
                         CHECK (decision IN ('APPROVE', 'REJECT')),
    comment_text         TEXT,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_insight_review_actor UNIQUE (proposal_id, actor)
);
CREATE INDEX idx_insight_reviews_proposal ON insight_proposal_reviews (proposal_id, created_at);

-- External-task creation time: the start edge of the latency signal. Records
-- created before this migration keep NULL and only terminal facts with a
-- known start reach the analyzer.
ALTER TABLE external_tasks ADD COLUMN created_at TIMESTAMP WITH TIME ZONE;
