-- E12: the project event stream tails committed outbox rows. Portable SQL (H2 and PostgreSQL).

-- seq orders rows for the stream and its Last-Event-ID resume. It is assigned
-- at insert, so the tailer holds a gap briefly for a transaction that may still
-- commit. Rows written before this migration are numbered in storage order;
-- the stream starts at the newest row when a replica starts.
ALTER TABLE outbox_events ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- The project an event belongs to, so the stream filters without a join.
-- Null for events outside any instance (deployments, price changes).
ALTER TABLE outbox_events ADD COLUMN project_id VARCHAR(255);
CREATE INDEX idx_outbox_project_seq ON outbox_events (project_id, seq);
CREATE INDEX idx_outbox_seq ON outbox_events (seq);
