apiVersion: v1
kind: Service
metadata:
  name: abada-orun
  namespace: abada
  labels:
    app.kubernetes.io/name: abada-orun
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: abada-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: abada-orun
  ports:
    - name: http
      port: 5603
      targetPort: http
      protocol: TCP
